name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (staging, production)'
        required: true
      correlationId:
        description: 'Correlation ID from ChatOps'
        required: false
      manual_approval:
        description: 'Set true if this is approved'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Deploy step (placeholder)
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }}"
          echo "CORRELATION=${{ github.event.inputs.correlationId }}"
          sleep 10
